# .github/workflows/email.ymal
name: Email Automation Cron

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '55 * * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Invoke API route/endpoint
        run: |
          curl --request POST \
          --url 'https://denotifier.com/api/email' \
          --header 'Authorization: Bearer ${{secrets.API_KEY}}'