name: Email Automation Cron
on:
  schedule:
    - cron: '*/5 * * * * '
  jobs:
    cron:
      runs-on: ubuntu-latest
      steps:
        - name: Invoke API route/endpoint
          run: |
            curl --request POST \
            --url 'https://denotifier.com/api/email' \
            --header 'Authorization: Bearer ${{secrets.API_KEY}}'